server:
    port: 7875

spring:
    datasource:
        # По умолчанию postgresql имеет 5432 порт. Но так как подразумевается запуск через docker-compose, указан порт
        # из docker-compose.yaml для корректной проброски. Если у вас локально установлен postgresql и вы собираетесь
        # использовать его, то требуется поменить его на нужный
        url: jdbc:postgresql://localhost:5430/wallet
        username: wallet
        password: wallet
    flyway:
        enabled: true
        locations:
          - db.migration
    session:
      store-type: jdbc
    security:
        user:
            password: qwerty
            name: wallet

    jpa:
      hibernate:
          ddl-auto: update
